"""model changes in followers following functionality added

Revision ID: 066417406229
Revises: fda7b9db2e6f
Create Date: 2024-03-14 11:46:56.160326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066417406229'
down_revision = 'fda7b9db2e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
